//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CloudNotes.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class ClientPackage : AggregateRootBase
	{
		public virtual string ClientType
		{
			get;
			set;
		}

		public virtual string ReleaseNotes
		{
			get;
			set;
		}

		public virtual DateTime DatePublished
		{
			get;
			set;
		}

		public virtual string Description
		{
			get;
			set;
		}

		public virtual string PublishedBy
		{
			get;
			set;
		}

		public virtual string PackageFileName
		{
			get;
			set;
		}

		public virtual string Version
		{
			get;
			set;
		}

	}
}

