//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CloudNotes.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Note : AggregateRootBase
	{
		public virtual string Title
		{
			get;
			set;
		}

		public virtual string Content
		{
			get;
			set;
		}

		public virtual DateTime DatePublished
		{
			get;
			set;
		}

		public virtual Nullable<DateTime> DateLastModified
		{
			get;
			set;
		}

		public virtual Weather Weather
		{
			get;
			set;
		}

		public virtual Nullable<DeleteFlag> Deleted
		{
			get;
			set;
		}

		public virtual string Description
		{
			get;
			set;
		}

		public virtual string ThumbnailBase64
		{
			get;
			set;
		}

		public virtual User User
		{
			get;
			set;
		}

	}
}

