//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CloudNotes.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Permission : AggregateRootBase
	{
		public virtual PermissionValue Value
		{
			get;
			set;
		}

		public virtual Privilege Privilege
		{
			get;
			set;
		}

		public virtual Role Role
		{
			get;
			set;
		}

	}
}

