//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CloudNotes.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class User : AggregateRootBase
	{
		public virtual string UserName
		{
			get;
			set;
		}

		public virtual string Password
		{
			get;
			set;
		}

		public virtual DateTime DateRegistered
		{
			get;
			set;
		}

		public virtual string Email
		{
			get;
			set;
		}

		public virtual Nullable<DateTime> DateLastAuthenticated
		{
			get;
			set;
		}

		public virtual bool Locked
		{
			get;
			set;
		}

		public virtual List<Note> Notes
		{
			get;
			set;
		}

		public virtual List<Role> Roles
		{
			get;
			set;
		}

	}
}

